config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'questions#index'
  get '/about', to: 'static_pages#about', as: 'about'
  get 'questions/closed_questions_index', to:'questions#closed_questions_index', as:"closed_questions_index"
  resources :questions
  resources :comments
  post '/comments/:id/like', to: 'likes#create', as: 'like'
  delete '/comments/:id/like', to: 'likes#destroy'
  get 'question/tie_breaker/:id', to: 'questions#tie_breaker', as: 'tie_breaker'
  post 'likes/final_likes/:id', to: 'likes#final_like', as: 'final_like'
end

app/models/question.rb
class Question < ApplicationRecord
    validates :title, presence: true, length: { maximum: 100 }
    validates :prize, presence: true, numericality: { greater_than_or_equal_to: 20 }
    validates :response_cost, presence: true, numericality: { greater_than_or_equal_to: 5 }
    validates :closing_date_and_time, presence: true
    validates :description, length: { maximum: 500 }
    has_many :comments, dependent: :destroy 
    has_one_attached :explaination_photo 
    belongs_to :user
    validate :has_enough_funds?
    validate :date_is_in_future?, :unless => :exists?



    def exists?
        !self.id.nil?
    end

    def is_active?
        if self.closing_date_and_time < DateTime.now 
            return false
        else 
            return true 
        end
    end

    def has_enough_funds?
        if self.id
            return true
        else 
            errors.add(:prize, "can not be greater than your account balance") if user.balance < prize
        end
    end

    def needs_tie_breaker?
        if self.active == false && self.prize_given == false 
            return true
        else 
            return false
        end
    end

    def date_is_in_future?
        if self.closing_date_and_time > DateTime.now 
            return true 
        else
            errors.add(:closing_date_and_time, "must be after current time")
        end
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_question, only: [:show, :destroy, :question_active?, :tie_breaker, :edit, :update]
    before_action :check_auth, only: [:create, :destroy, :edit, :update]
    before_action :question_active?, only: [:show]
    before_action :deactivate_old_questions, only: [:index]
    before_action :decide_winner, only: [:index]
    def index
        # checking if any of the questions that the user has made needs a tie breaker and then redirectiing them to the tie breaker page for that question. 
        # If they do not need to go to thd tie breaker page then we are given a list of questions that are active. Then the most recent win is grabbed from the most recent win table.
        questions_that_need_tie_breaking = Question.where(user_id: current_user.id, active: false, prize_given: false).select{|question| question.needs_tie_breaker?}
        if !questions_that_need_tie_breaking.empty? 
            redirect_to tie_breaker_path(questions_that_need_tie_breaking[0].id)
        end
        @questions = Question.where(active: true).sort_by{|question| question.prize}.reverse
        @most_recent_win = MostRecentWin.last
    end

    def closed_questions_index
        # getting all of the inactive question for the closed questions index and then sorting them by the most receently updated (aka most recently closed off)
        @questions = Question.where(active: false).sort_by{|question| question.updated_at}
    end

    def show
        # Opening a new instance of a comment so my form knows what element the form is for
        @comment = Comment.new
        @comments = @question.comments.sort_by{|comment| comment.likes.count}.reverse
    end 

    def new
        # Opening a new instance of a comment so my form knows what element the form is for
        @question = Question.new
        check_auth
        @current_user = current_user
    end
    
    def create
        # This method creates the new question. Checks that there is a prize specified, if there isn't then it will set it as 0 so that it will fail validation rather than throw and error
        # If the saving fails then it rerenders the 'new' page
        @question = Question.new(question_params)
        if !@question.prize.nil?
            @question.prize = @question.prize.round(2) 
        else 
            @question.prize = 0
        end
        if !@question.response_cost.nil?
            @question.response_cost = @question.response_cost.round(2) 
        else 
            @question.response_cost = 0
        end
        @question.user_id = current_user.id
        if @question.save
            current_user.balance -= question_params[:prize].to_i
            current_user.save
            redirect_to @question
        else
            render action: 'new'
        end
    end
    
    
    def destroy
        # This destroys a question and then takes them back to the home page
        @question.destroy
        redirect_to root_path
    end

    def edit
        # This method just sets the question in the before action and then sends them to the edit page
    end

    def update
        # This method updates a question with the allowed params and then sends them back to the root path. If it fails, it adds errors to the flash errors and re renders the edit page
        if @question.update(update_question_params)
            @question.update(update_question_params)
            redirect_to root_path
        else
            flash.now[:errors] = @question.errors.full_messages
            render action: 'edit'
        end
    end

    
    def tie_breaker
        # This is the method that makes the list of questions that need tie breaking. Then redircts the user to the tie breaker page. 
        most_likes = @question.comments.sort_by{|comment| comment.likes.count}.last.likes.count
        @questions_that_need_tie_breaking = []
        @question.comments.each do |comment|
            if comment.likes.count == most_likes 
                @questions_that_need_tie_breaking.push(comment)
            end
        end
    end



    private
    def needs_tie_breaker?(question)
        # This is a method that checks where a specified comment neeeds a tie breaker by checking if the top two comments have the same number of likes 
        sorted_by_likes = question.comments.sort_by{|comment| comment.likes.count}
        if sorted_by_likes.last.likes.count == sorted_by_likes[-2].likes.count
            return true
        else
            return false
        end
    end
    
    def set_question 
        # This is to set the question passed on what page the user is on. 
        @question = Question.find(params[:id])
    end

    def question_params
        # This sets the allowed fields for making a question as well as saying that it must be in the hash question.
        params.require(:question).permit(:title, :description, :prize, :response_cost, :closing_date_and_time, :explaination_photo )
    end

    def update_question_params
        # This sets the allowed fields for updating a question as well as stating it must be inside the hash
        params.require(:question).permit(:title, :description, :closing_date_and_time, :explaination_photo )
    end

    def check_auth
        # This checks if a user that is trying to do an action has the authority in the question policy to do it. We run this as a before action on the sensitive actions. CHECK THIS ONE 
        begin 
            authorize @question
        rescue 
            authorize Question
        end
    end

    def question_active?
        # This is an action that checks whether an question is actually active as this allows the question to close while still inside the show action (because the deactiving is run on the index page)
        @active = @question.closing_date_and_time > DateTime.now
    end

    def deactivate_old_questions
        # This is an action that checks all active questions and sees if they need to be changed to not active
        @questions = Question.where(active: true)
        @questions.each do |question|
            question.active = question.is_active?
            question.save 
        end 
    end 

    def decide_winner
        # This is the action that decides the winner of a question. If there are no comments on a page then the money goes to the admin, if there are comments and they don't need a tie breaker. Then sort by most likes and pick the most liked question 
        questions = Question.where(active: false, prize_given: false)
        if questions 
            questions.each do |question|
                if question.comments.count == 0
                    admin = User.find_by(email: "admin@a.com")
                    admin.balance += question.prize
                    admin.save
                    question.prize_given = true
                    question.save
                elsif question.comments.count == 1 or !needs_tie_breaker?(question)
                    winning_comment = question.comments.sort_by{|comment| comment.likes.count}.last
                    winning_user = winning_comment.user
                    winning_user.balance += winning_comment.question.prize
                    winning_user.save
                    question.prize_given = true
                    question.save
                    MostRecentWin.last.update(title: question.title, comment: winning_comment.body, user: winning_user.username, prize: question.prize)
                end
            end
        end
    end
end 

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= simple_form_for @question do |f| %>
        <%= f.error_notification %>
        <%= f.hidden_field :user, value: @current_user.id%>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :prize%>
        <%= f.input :response_cost%>        
        <%= f.input :closing_date_and_time, :as => :datetime %>
        <%= f.input :explaination_photo%>    
        <%= f.submit %>
        <button><%= link_to "Cancel", root_path %></button>
<% end %>

app/views/questions/closed_questions_index.html.erb
<h1>Closed Questions </h1>
<% if user_signed_in? %>
    <h2><%= link_to "New question", new_question_path %></h2>
<% end %>


<div class="d-flex align-content-stretch flex-wrap justify-content-around"> 
    <% @questions.each do |question|%>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <p>Posted by: <strong><%= question.user.username%></strong></p>
            <p>Closed on <strong><%=question.closing_date_and_time.to_date%></strong></p>
                <h5 class="card-title"><%= link_to question.title, question_path(question) %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= question.prize %> | <%= question.response_cost %> </h6>
                <p><%= truncate(question.description, :length => 100) if question.description %></p>
                <span><%=Comment.where(question_id: question.id).count%> reponses<span>
                <% if user_signed_in? && policy(Question).destroy?%>
                    <p><%= link_to "Delete", question_path(question), method: :delete, data: {confirm: "Are you sure you would like to delete this question?"} %></p>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/questions/edit.html.erb
<h1> Edit question </h1>
<%= simple_form_for @question do |f| %>
        <%= f.error_notification %>
        <%= f.input :title %>
        <%= f.input :description %>       
        <%= f.input :closing_date_and_time, :as => :datetime %>
        <%= f.input :explaination_photo%>    
        <%= f.submit %>
        <button><%= link_to "Cancel", root_path %></button>
<% end %>

app/views/questions/index.html.erb
<h1>Questions </h1>
<% if @most_recent_win%>
    <p>Congratulations to <strong><%=@most_recent_win.user%></strong> on their win of <strong>$<%=@most_recent_win.prize%></strong> on question "<%= @most_recent_win.title%>" with their response "<%= @most_recent_win.comment%>"</p>
<% end %>
<% if user_signed_in? %>
    <h2><%= link_to "New question", new_question_path %></h2>
<% end %>
<div class="d-flex align-content-stretch flex-wrap justify-content-around">
    <% @questions.each do |question|%>
        <div class="card" style="width: 20rem;">
            <div class="card-body">
            <p>Posted by: <strong><%= question.user.username%></strong></p>
                <h5 class="card-title"><%= link_to question.title, question_path(question) %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= question.prize %> | <%= question.response_cost %> </h6>
                <p><%= truncate(question.description, :length => 100) if question.description %></p>
                <span><%=Comment.where(question_id: question.id).count%> reponses<span>
                <p><%=distance_of_time_in_words(DateTime.now, question.closing_date_and_time) %> left</p>
                <% if user_signed_in? && policy(Question).destroy?%>
                    <p><%= link_to "Delete", question_path(question), method: :delete, data: {confirm: "Are you sure you would like to delete this question?"} %></p>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/questions/new.html.erb
<h1>Make a new question</h1>
<%=render "form"%>

app/views/questions/show.html.erb
<h1>Show page</h1>
<p>Posted by: <strong><%= @question.user.username%></strong></p>
<p><%= @question.title %></p> 
<p><%= @question.description  %></p>
<div>
<%= @question.prize %> 
|
<%= @question.response_cost %> 
</div>
<% if @active %>
    <%time_remaining = @question.closing_date_and_time - DateTime.now%>
    <strong>Time remaining:</strong><%= ActiveSupport::Duration.build(time_remaining.round).inspect %>
<% else %>
    <strong>Time remaining:</strong> QUESTION CLOSED
<%end%>
<% if @question.explaination_photo.attached? %>
    <p><%= cl_image_tag @question.explaination_photo.key, crop: :scale, width: 500, cloud_name: 'bene' %></p>
<% end %>

<% if policy(Question).destroy? %>
    <p><%= link_to "Delete Question", question_path(@question), method: :delete, data: {confirm: "Are you sure you would like to delete this question?"} %></p>
<% end %>
<% if policy(@question).edit? && @question.active %>
    <p><%= link_to "Edit Question", edit_question_path(@question) %></p>
<% end %>


<% if @active %>
    <%= form_with model: @comment, local: true do |f| %>
        <%= f.hidden_field :question_id, value: @question.id %>
        <%= f.text_area :body, placeholder: "add a comment" %>
        <%= f.submit %>
    <% end %>
<% end %>
<hr>
    <% @comments.each do |comment| %>
    <div class="card" style="width: 25rem;">
        <div class="card-body">
            <h5 class="card-title">Posted by: <%= comment.user.username%></h5>
            <p class="card-text"><%= comment.body %></p>
            <p class="card-text"><%= pluralize(comment.likes.count, "like")%></p>
            <% if user_signed_in? && @question.user_id != current_user.id && @question.active %>
                <% if comment.liked?(current_user) %>
                    <%= button_to "Unlike", like_path(comment), method: :delete, class:"btn btn-primary" %>
                <% else %>
                    <%= button_to "like", like_path(comment), method: :post, class:"btn btn-primary" %>
                <% end %>
            <% end %>
            <% if policy(Comment).destroy? %>
                <h5><%= link_to "Delete", comment_path(comment), method: :delete, data: {confirm: "Are you sure you would like to delete this comment?"}%></h5>
            <% end %>
        </div>
    </div>
    <% end %>














<% if @question.comments.count == 0 && @question.active %>
    <h1>🐶</h1>
    <h3>Wow, such empty </h3>
<% elsif @question.comments.count == 0 && !@question.active %>
    <h3>No one responded to this question :(</h3>
<% end %>

app/views/questions/tie_breaker.html.erb
<h1>Tie breaker</h1>
<p>Your question "<strong><%= @question.title %></strong>" ended in a tie. Please choose your favourite response and we will give the prize to them. </p>
<p>worth: $<%= @question.prize%></p>
<div class="d-flex align-content-stretch flex-wrap justify-content-around">
  <% @questions_that_need_tie_breaking.each do |comment|%>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Posted by: <%= comment.user.username %></h5>
      <p class="card-text"><%= comment.body%></p>
      <p class="card-text"><%= pluralize(comment.likes.count, "like")%></p>
      <%= button_to "like", final_like_path(comment), method: :post, class:"btn btn-primary" %>
    </div>
  </div>
  <% end %>
</div>





 