config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'questions#index'
  get '/about', to: 'static_pages#about', as: 'about'
  get 'questions/closed_questions_index', to:'questions#closed_questions_index', as:"closed_questions_index"
  resources :questions
  resources :comments
  post '/comments/:id/like', to: 'likes#create', as: 'like'
  delete '/comments/:id/like', to: 'likes#destroy'
  get 'question/tie_breaker/:id', to: 'questions#tie_breaker', as: 'tie_breaker'
  post 'likes/final_likes/:id', to: 'likes#final_like', as: 'final_like'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaLab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" defer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous" defer></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container db-flex">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a  href="#"><%=  link_to "Home", root_path , class:"navbar-brand"%></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <a class="nav-link active" aria-current="page" href="#"><%= link_to "Closed Questions", closed_questions_index_path, class:"navbar-brand" %></a>
            <a class="nav-link active" aria-current="page" href="#"><%= link_to "About", about_path, class:"navbar-brand" %></a>
      </div>
  </nav>

    <% if current_user %>
      <%= current_user.username%> | 
      $<%= current_user.balance.round(2) %> | 
      <%= current_user.email %>
      |
      <%= link_to "Logout", destroy_user_session_path, method: :delete	%>
    <% else %>
      <%= link_to "Sign_in", new_user_session_path %>
      |
      <%= link_to "Sign_up", new_user_registration_path %>
    <% end %>




    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.respond_to?('each') %>
      <p class="alert">
      <ul>
        <% alert.each do |individual_alert| %></p>
          <li><%= individual_alert %></li>
        <% end %>
      </ul>
    <% elsif alert %>
      <p class="alert"><%= alert %>
    <% end %>
    <% if flash[:errors] %>
      <section class="errors">
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
      </section>
    <% end %>
    <hr>
    <%= yield %>
  </body>
</html>